#!/bin/bash

# This script is run by Supervisor to start OMERO in foreground mode

set -e
set -u
set -x

export OMERO_HOME=/opt/omero
export PATH=$OMERO_HOME/bin:$PATH
BRANCH=OMERO-5.0-latest

mkdir -p /data/OMERO
chown omero:omero /data/OMERO

if [ ! -d /opt/omero ]
then
    cd /tmp
    /home/omero/venv/bin/omego download server --branch=$BRANCH --labels ICE=3.4
    rm OMERO.server*zip
    chown -R omero:omero OMERO.server*
    mv OMERO.server* /opt/
    ln -s /opt/OMERO.server* /opt/omero
fi

rm -rf /opt/omero/var
mkdir -p /opt/omero/var
mkdir -p /opt/omero/var/master
mkdir -p /opt/omero/var/registry

mkdir -p /data/logs
chown -R omero:omero /data/logs
chown -R omero:omero /opt/omero/var/

ln -s /data/logs /opt/omero/var/log
