#!/bin/bash

i="0"

while [ $i -lt 10 ]
do
    /usr/lib/postgresql/9.1/bin/pg_ctl -D /data/postgresql status -w 2>/dev/null && exit 0
    echo "waiting on postgresql..."
    sleep 1
    i=$[$i+1]
done
