#!/bin/bash

# This script is run by Supervisor to start OMERO in foreground mode

set -e
set -u
set -x

cd /opt/omero
su omero -c 'bin/omero web syncmedia'

cd lib/python/omeroweb
export PYTHONPATH=.:/opt/omero/lib/python
exec su omero -c 'python manage.py runserver 0.0.0.0:4080 --noreload --nothreading'
