#!/bin/bash

# Setup and run omero

set -eux

if [ $# -eq 0 ]; then
    OPTS="${OMEGO_ARGS:-}"
else
    OPTS="$@"
fi

while ! psql -Uomero -l > /dev/null; do
    echo "Waiting for postgres"
    sleep 5
done

# Create the omero database if it doesn't already exist
DBCMD=--upgradedb
psql -Uomero omero -c '\conninfo' || {
    echo "Creating omero database"
    su - omero -c "createdb -E UTF8 -O omero omero"
    su - omero -c "psql -c \"ALTER ROLE omero WITH PASSWORD 'omero'\""
    DBCMD=--initdb
}

if [ ! -d /data/OMERO ]; then
    echo "Creating omero data directory"
    mkdir -p /data/OMERO
    chown -R omero /data/OMERO
fi

PRESTART=
if stat -t /data/omero.preload/* > /dev/null 2>&1; then
    for f in /data/omero.preload/*; do
        PRESTART="$PRESTART --prestartfile $f"
    done
fi

OMERO=~omero/OMERO.server/bin/omero

if [ -e ~omero/OMERO.server ]; then
    echo "OMERO.server found, starting existing server"
    su - omero -c "$OMERO admin start"
    su - omero -c "$OMERO web start"
else
    su - omero -c \
        "omego install $DBCMD --dbname omero --sym OMERO.server $PRESTART $OPTS"
fi

echo "Creating web configuration"
su - omero -c "$OMERO web config nginx" > /etc/nginx/conf.d/omero-web.conf

echo "Restarting nginx"
supervisorctl restart nginx
